# Generated by Django 6.0 on 2025-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('eligible', models.BooleanField()),
            ],
        ),
    ]
